services:

  postgres:
    image: postgres:16
    container_name: desafio_postgres

    environment:
      POSTGRES_DB: cooperativa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  spark:
    image: apache/spark:3.5.9-scala2.12-java17-python3-ubuntu
    container_name: desafio_spark

    depends_on:
      - postgres

    environment:
      SPARK_SUBMIT_OPTS: "-Divy.cache.dir=/tmp/.ivy2/cache -Divy.home=/tmp/.ivy2"

    volumes:
      - ./src:/opt/spark/work-dir/src
      - ./output:/opt/spark/work-dir/output

    command: ["sleep", "infinity"]

volumes:
  postgres_data: