services:

  postgres:
    image: postgres:16
    container_name: desafio_postgres

    environment:
      POSTGRES_DB: cooperativa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cooperativa"]
      interval: 5s
      timeout: 5s
      retries: 10


  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark

    image: desafio-spark
    container_name: desafio_spark

    depends_on:
      - postgres

    environment:
      SPARK_SUBMIT_OPTS: "-Divy.cache.dir=/tmp/.ivy2/cache -Divy.home=/tmp/.ivy2"

    volumes:
      - ./:/opt/spark/work-dir

    command: ["sleep", "infinity"]

  etl:
    image: desafio-spark
    container_name: desafio_etl

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPARK_SUBMIT_OPTS: "-Divy.cache.dir=/tmp/.ivy2/cache -Divy.home=/tmp/.ivy2"

    volumes:
      - ./:/opt/spark/work-dir

    command:
      [
        "/opt/spark/bin/spark-submit",
        "--packages",
        "org.postgresql:postgresql:42.7.7",
        "/opt/spark/work-dir/src/etl.py",
        "output"
      ]

volumes:
  postgres_data: